# Consulta do Registro Restrito de Clientes

Este notebook consulta exclusivamente o arquivo `data/restricted/customer_identity_map.parquet`.

O arquivo contém dados pessoais e sensíveis. Execute este notebook somente em ambiente autorizado e não compartilhe suas saídas.

In [5]:
from pathlib import Path

import pandas as pd

project_root = Path.cwd().resolve()
while project_root != project_root.parent and not (project_root / "data").is_dir():
    project_root = project_root.parent

restricted_path = (
    project_root
    / "data"
    / "restricted"
    / "customer_identity_map.parquet"
)

print(f"Arquivo: {restricted_path}")
assert restricted_path.exists(), f"Arquivo não encontrado: {restricted_path}"

Arquivo: C:\Users\Mileno\Downloads\Projeto LGPD\data\restricted\customer_identity_map.parquet

In [6]:
customer_identity_map = pd.read_parquet(restricted_path)

print(f"Registros: {len(customer_identity_map):,}")
print(f"Colunas: {len(customer_identity_map.columns)}")
print("\nNomes das colunas:")
print(list(customer_identity_map.columns))

print("\nTipos das colunas:")
display(customer_identity_map.dtypes.rename("tipo").to_frame())

Registros: 10,000
Colunas: 25

Nomes das colunas:
['customer_id', 'nome', 'cpf', 'email', 'telefone', 'data_nascimento', 'sexo', 'raca_etnia', 'cidade', 'estado', 'cep', 'profissao', 'renda_mensal', 'estado_civil', 'possui_filhos', 'condicao_saude', 'tipo_sanguineo', 'consentimento_marketing', 'data_consentimento', 'data_cadastro', 'ultima_compra', 'quantidade_compras', 'valor_total_compras', 'canal_preferido', 'customer_id_protected']

Tipos das colunas:

                            tipo
customer_id                  str
nome                         str
cpf                          str
email                        str
telefone                     str
data_nascimento           object
sexo                         str
raca_etnia                   str
cidade                       str
estado                       str
cep                          str
profissao                    str
renda_mensal             float64
estado_civil                 str
possui_filhos               bool
condicao_saude               str
tipo_sanguineo               str
consentimento_marketing     bool
data_consentimento        object
data_cadastro             object
ultima_compra             object
quantidade_compras         int64
valor_total_compras      float64
canal_preferido              str
customer_id_protected        str

In [7]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.max_colwidth", 80)

display(customer_identity_map.head(10))

,customer_id,nome,cpf,email,telefone,data_nascimento,sexo,raca_etnia,cidade,estado,cep,profissao,renda_mensal,estado_civil,possui_filhos,condicao_saude,tipo_sanguineo,consentimento_marketing,data_consentimento,data_cadastro,ultima_compra,quantidade_compras,valor_total_compras,canal_preferido,customer_id_protected
0,23b8c1e9-3924-46de-beb1-3b9046685257,Srta. Ísis Borges,960.781.425-85,zoeleao@example.org,(041) 9402-6542,1984-03-28,Masculino,Preta,Teixeira,BA,11615-594,Médico,14822.66,União Estável,True,Infecção por HIV,O+,True,2022-10-09,2022-09-01,2025-10-26,4,37103.37,Email,9a56faa398e739ee3e38b7a6796847f96bee3182920ef1713e330ba3fedaae3a
1,60e7a113-ec1b-4ca1-b91e-1d4c1ff49b78,Yuri da Rocha,953.806.174-84,guilhermegarcia@example.com,(051) 5255-3419,1995-08-26,Outro,Indígena,Nascimento,AC,27648350,Administrador,15775.51,União Estável,False,Asma,O-,True,2025-12-30,2022-02-02,2026-08-26,12,11010.03,SMS,2cdb0f55d0ae64f28f35df585624d50dc15af5ebdc4dd74ef9506f9c634a3ee0
2,e9c349e0-3602-48ac-90f1-bc81448aaa9e,Luara Cunha,769.128.453-55,zpacheco@example.com,+55 21 2871-0122,1956-04-24,Outro,Amarela,Peixoto de Minas,MT,69784-801,Vendedor,5470.00,Divorciado,True,Hipertensão,O+,True,2024-09-04,2021-12-29,2025-05-28,98,40310.38,Email,23cc68e3025de04fcb2b10f0ea28337a676a8c820fca0e3a9a2f0a706d2c5e80
3,5715bd6f-a416-4293-84c2-e2e3444ea7c8,Juan Lopes,270.569.148-02,natalia93@example.org,31 2880 9570,1987-02-12,Masculino,Outro,Fonseca,PB,30391-171,Médico,25623.36,Viúvo,True,TEA,AB+,False,None,2026-04-16,2026-09-08,45,30225.93,SMS,e3ad201c591c755e4b9c2858881314cc247e6b1a979c5b52c8043bd755745e19
4,f264accc-79ac-4b1e-a8e5-6e0c20de435d,Eloah da Luz,863.451.297-55,cmoreira@example.org,+55 51 3150 9839,2007-04-11,Outro,Preta,Abreu,SP,03105183,Analista de Sistemas,26755.06,Casado,True,Obesidade,AB+,True,2026-08-29,2026-04-03,2026-04-27,91,3570.80,Aplicativo,958728b2ba9d18320d4b29becef45a730b8aa70da17a03f1dec01cc3768308af
5,ef7ddc76-b92d-422b-a1df-306f8a0b3c33,Olívia da Cruz,763.089.214-40,dsiqueira@example.net,+55 41 0651 3338,1959-09-04,Masculino,Outro,Carvalho de Lima,GO,47317810,Professor,13311.86,Casado,True,Diabetes,O-,False,None,2025-11-07,2026-01-29,21,18572.03,Aplicativo,b10bea20d4b29f74aef94f263849bc3a7556cf7eacabee1d6bb2b8a76ada2780
6,c0e9ab30-ed26-42e9-97e0-11b7f8102383,Enzo Jesus,793.680.154-57,yda-luz@example.com,(011) 6872 3430,1985-02-07,Masculino,Outro,Souza,MT,00978-820,Engenheiro de Software,6562.78,Solteiro,False,Obesidade,AB+,False,None,2026-04-27,2026-04-29,82,34439.28,Email,9577d97fd856b18790ee7b9a2ad9d56ef596a94b051f303ac8acfef54dca3313
7,acdabacc-1165-4210-9854-3881118a9d29,Nathan Campos,930.478.215-50,rhavi46@example.org,(031) 7510 7991,2006-02-08,Feminino,Preta,Nascimento,RS,84251354,Customer Success,9248.80,Viúvo,True,Doença cardiovascular,B+,True,2026-02-15,2026-01-15,2026-03-28,73,43830.74,WhatsApp,bec557ca01c1a2ff44ef974a34d996f5d4ded974952eac495281363b84f76f40
8,fbddcf7c-9c96-49ec-8d71-c366b41b3143,Vitória Albuquerque,841.720.953-05,alexia93@example.net,(081) 3487 4016,1951-06-17,Outro,Amarela,Aparecida do Sul,MS,24278-680,Contador,28619.64,Casado,False,Hipertensão,A+,False,None,2025-06-13,2026-08-08,96,29270.84,Email,6c489493f7f8c12bbf55454ac6611ee2a0bb80d127adc439c4453c8d25525777
9,8d7248e2-951f-48d0-9e84-f058d5a804eb,Pedro Cardoso,045.692.187-76,fogacajoana@example.net,+55 (021) 3226-0256,1948-05-03,Outro,Amarela,da Mata,RN,16073375,Professor,9063.11,União Estável,False,TEA,AB+,True,2023-08-18,2022-05-12,2022-08-31,81,8083.10,Email,8bd21cedd7cfe34d9fc1e062dde0bb7e80357f07bfac20d8a2a9090e9bb6b313

## Consulta completa

A variável `customer_identity_map` contém o DataFrame completo. Para visualizar todos os registros na saída, execute a célula abaixo. Isso pode gerar uma saída grande e expor dados pessoais na interface do notebook.

In [8]:
# Execute somente quando for necessário visualizar todos os registros.
display(customer_identity_map)

,customer_id,nome,cpf,email,telefone,data_nascimento,sexo,raca_etnia,cidade,estado,cep,profissao,renda_mensal,estado_civil,possui_filhos,condicao_saude,tipo_sanguineo,consentimento_marketing,data_consentimento,data_cadastro,ultima_compra,quantidade_compras,valor_total_compras,canal_preferido,customer_id_protected
0,23b8c1e9-3924-46de-beb1-3b9046685257,Srta. Ísis Borges,960.781.425-85,zoeleao@example.org,(041) 9402-6542,1984-03-28,Masculino,Preta,Teixeira,BA,11615-594,Médico,14822.66,União Estável,True,Infecção por HIV,O+,True,2022-10-09,2022-09-01,2025-10-26,4,37103.37,Email,9a56faa398e739ee3e38b7a6796847f96bee3182920ef1713e330ba3fedaae3a
1,60e7a113-ec1b-4ca1-b91e-1d4c1ff49b78,Yuri da Rocha,953.806.174-84,guilhermegarcia@example.com,(051) 5255-3419,1995-08-26,Outro,Indígena,Nascimento,AC,27648350,Administrador,15775.51,União Estável,False,Asma,O-,True,2025-12-30,2022-02-02,2026-08-26,12,11010.03,SMS,2cdb0f55d0ae64f28f35df585624d50dc15af5ebdc4dd74ef9506f9c634a3ee0
2,e9c349e0-3602-48ac-90f1-bc81448aaa9e,Luara Cunha,769.128.453-55,zpacheco@example.com,+55 21 2871-0122,1956-04-24,Outro,Amarela,Peixoto de Minas,MT,69784-801,Vendedor,5470.00,Divorciado,True,Hipertensão,O+,True,2024-09-04,2021-12-29,2025-05-28,98,40310.38,Email,23cc68e3025de04fcb2b10f0ea28337a676a8c820fca0e3a9a2f0a706d2c5e80
3,5715bd6f-a416-4293-84c2-e2e3444ea7c8,Juan Lopes,270.569.148-02,natalia93@example.org,31 2880 9570,1987-02-12,Masculino,Outro,Fonseca,PB,30391-171,Médico,25623.36,Viúvo,True,TEA,AB+,False,None,2026-04-16,2026-09-08,45,30225.93,SMS,e3ad201c591c755e4b9c2858881314cc247e6b1a979c5b52c8043bd755745e19
4,f264accc-79ac-4b1e-a8e5-6e0c20de435d,Eloah da Luz,863.451.297-55,cmoreira@example.org,+55 51 3150 9839,2007-04-11,Outro,Preta,Abreu,SP,03105183,Analista de Sistemas,26755.06,Casado,True,Obesidade,AB+,True,2026-08-29,2026-04-03,2026-04-27,91,3570.80,Aplicativo,958728b2ba9d18320d4b29becef45a730b8aa70da17a03f1dec01cc3768308af
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,cf521922-e668-4003-98cb-bcab921746a7,Lorena Brito,128.736.504-35,mathias80@example.com,+55 (071) 9585-4940,1947-02-19,Outro,Outro,Souza,CE,94978857,Engenheiro Civil,21891.44,União Estável,True,Alergia crônica,AB-,False,None,2023-08-23,2025-09-12,66,14410.86,SMS,7e9dffb7b21a65e7200f3515a2f05a4360f6b26e3bd7204c7fec883099408296
9996,beccfb34-be16-4736-a0ff-6143aa074265,Ester Cardoso,923.106.845-89,raul43@example.org,+55 84 3491 3295,1969-08-29,Feminino,Parda,Garcia,DF,71988789,Engenheiro Civil,18345.07,União Estável,False,Depressão,B+,False,None,2024-10-21,2025-01-18,43,12485.11,WhatsApp,e07de168179dd08fbe64224c5603592adbac4ebfe1ab274e3cd9207173c572a4
9997,b2b50540-30f2-40b3-bf06-f39e0c44ca33,Theo Rocha,403.657.821-90,esales@example.net,+55 31 0749 6359,1958-03-06,Masculino,Indígena,Correia do Sul,RO,85218023,Professor,11361.31,Casado,False,Depressão,A+,True,2025-03-30,2025-03-23,2025-07-21,90,19475.78,Email,5dad5c74624738f1d1a5d80817d7d9375c2a03ebb7d72f6100f8c2c3d492bc3e
9998,721d855a-5d78-40c0-ac21-68937acaa671,Sr. Arthur Gabriel Viana,180.429.756-94,vitorabreu@example.org,+55 (011) 9657-3164,1995-04-13,Feminino,Outro,Sales Alegre,PA,58369263,Técnico de TI,14282.49,Viúvo,True,TEA,AB-,True,2026-07-03,2025-01-24,2026-05-31,42,9834.91,WhatsApp,d50b3a8bea26f82c8a0b40e12538f4ec6b8f27d0bd412a704c8da9d2547d11bb
9999,756ef550-4ddf-48dd-9514-b2b9d7757671,Pietra Sá,957.214.036-16,sadaniel@example.net,+55 41 1017 1282,1976-09-02,Feminino,Preta,Moreira,PI,82421-182,Cientista de Dados,21991.35,Divorciado,True,Depressão,A+,False,None,2026-07-08,2026-08-29,57,8555.25,Email,97c015773d53e27288020500d6db4bb78e8b13023fa31d6358026b2d8f2ba85d